version: "3"
services:
  client:
    build: ./client
    restart: unless-stopped
    ports: ["0.0.0.0:3000:80"]
  server:
    build: ./server
    restart: unless-stopped
    ports: ["0.0.0.0:5000:5000"]
